title: '阿钊的写字板'
subtitle: ''
description: '公众号：阿钊的写字板'
keywords: '澄澈少年, Java, 全栈开发'
author: '阿钊'
url: http://blog.gotojava.cn/
root: /
permalink: posts/:abbrlink.html
abbrlink:
  alg: crc32
  rep: hex
theme: Hacker

deploy:
  type: 'git'
  repo: https://github.com/yangzhao917/yangzhao917.github.io.git
  branch: page
  token: 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