title: '阿钊的写字板'
subtitle: '公众号：阿钊的写字板'
description: '专注于 Java 技术栈与分布式系统实践，分享技术难题攻克、系统优化实战与信创项目开发经验。'
keywords: '阿钊的写字板, Java, 分布式'
author: '阿钊的写字板'
url: http://blog.gotojava.cn/
root: /
permalink: posts/:abbrlink.html
abbrlink:
  alg: crc32
  rep: hex
theme: Hacker

deploy:
  type: 'git'
  repo: https://github.com/yangzhao917/yangzhao917.github.io.git
  branch: page
  token: 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